# CORPORATE STRESS

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**DATA UNDERSTANDING**

In [2]:
df=pd.read_csv("corporate_stress_dataset.csv")

In [3]:
df.columns

Index(['ID', 'Age', 'Gender', 'Marital_Status', 'Job_Role', 'Experience_Years',
       'Monthly_Salary_INR', 'Working_Hours_per_Week', 'Commute_Time_Hours',
       'Remote_Work', 'Stress_Level', 'Health_Issues', 'Company_Size',
       'Department', 'Sleep_Hours', 'Physical_Activity_Hours_per_Week',
       'Mental_Health_Leave_Taken', 'Manager_Support_Level',
       'Work_Pressure_Level', 'Annual_Leaves_Taken', 'Work_Life_Balance',
       'Family_Support_Level', 'Job_Satisfaction', 'Performance_Rating',
       'Team_Size', 'Training_Opportunities', 'Gender_Bias_Experienced',
       'Discrimination_Experienced', 'Burnout_Symptoms', 'Location'],
      dtype='object')

In [17]:

pd.set_option('display.max_columns', None)
print(df.head())

   ID  Age      Gender Marital_Status   Job_Role  Experience_Years  \
0   1   56  Non-Binary        Widowed  Developer                 5
1   2   46      Female         Single    Analyst                20
2   3   32      Female         Single  Developer                10
3   4   60      Female       Divorced    Analyst                26
4   5   25        Male        Married      Sales                29

   Monthly_Salary_INR  Working_Hours_per_Week  Commute_Time_Hours  \
0           102703.08                      44                1.72
1           165583.91                      54                0.62
2            38005.39                      81                1.22
3            51127.36                      79                2.03
4           174597.45                      63                1.45

   Remote_Work  Stress_Level Health_Issues Company_Size Department  \
0         True             0           NaN        Small  Marketing
1         True             7           NaN        Large         IT
2        False             7      Physical       Medium         HR
3        False             6        Mental        Small         IT
4         True             8          Both        Large      Sales

   Sleep_Hours  Physical_Activity_Hours_per_Week  Mental_Health_Leave_Taken  \
0          5.6                               1.9                      False
1          9.0                               3.5                       True
2          7.9                               8.4                      False
3          4.1                               6.4                       True
4          4.0                               9.2                       True

   Manager_Support_Level  Work_Pressure_Level  Annual_Leaves_Taken  \
0                      1                    0                   15
1                      7                   10                   12
2                      2                    7                   13
3                      6                    2                   15
4                      9                   10                   11

   Work_Life_Balance  Family_Support_Level  Job_Satisfaction  \
0                  9                     2                 5
1                  9                     1                10
2                  6                     1                 1
3                  8                    10                 5
4                  3                     1                 9

   Performance_Rating  Team_Size  Training_Opportunities  \
0                  10         38                   False
1                   9         72                    True
2                   1         67                   False
3                  10         98                    True
4                   2         85                    True

   Gender_Bias_Experienced  Discrimination_Experienced Burnout_Symptoms  \
0                     True                        True               No
1                     True                        True               No
2                    False                       False              Yes
3                     True                       False              Yes
4                    False                       False               No

  Location
0   Tier-3
1   Tier-3
2    Metro
3    Metro
4   Tier-1

In [18]:
df.head()

,ID,Age,Gender,Marital_Status,Job_Role,Experience_Years,Monthly_Salary_INR,Working_Hours_per_Week,Commute_Time_Hours,Remote_Work,Stress_Level,Health_Issues,Company_Size,Department,Sleep_Hours,Physical_Activity_Hours_per_Week,Mental_Health_Leave_Taken,Manager_Support_Level,Work_Pressure_Level,Annual_Leaves_Taken,Work_Life_Balance,Family_Support_Level,Job_Satisfaction,Performance_Rating,Team_Size,Training_Opportunities,Gender_Bias_Experienced,Discrimination_Experienced,Burnout_Symptoms,Location
0,1,56,Non-Binary,Widowed,Developer,5,102703.08,44,1.72,True,0,NaN,Small,Marketing,5.6,1.9,False,1,0,15,9,2,5,10,38,False,True,True,No,Tier-3
1,2,46,Female,Single,Analyst,20,165583.91,54,0.62,True,7,NaN,Large,IT,9.0,3.5,True,7,10,12,9,1,10,9,72,True,True,True,No,Tier-3
2,3,32,Female,Single,Developer,10,38005.39,81,1.22,False,7,Physical,Medium,HR,7.9,8.4,False,2,7,13,6,1,1,1,67,False,False,False,Yes,Metro
3,4,60,Female,Divorced,Analyst,26,51127.36,79,2.03,False,6,Mental,Small,IT,4.1,6.4,True,6,2,15,8,10,5,10,98,True,True,False,Yes,Metro
4,5,25,Male,Married,Sales,29,174597.45,63,1.45,True,8,Both,Large,Sales,4.0,9.2,True,9,10,11,3,1,9,2,85,True,False,False,No,Tier-1

In [19]:
df.shape

(50000, 30)

In [34]:
df['Stress_Level'].value_counts()

Stress_Level
9     4659
5     4636
2     4598
4     4575
1     4552
7     4533
3     4532
6     4500
8     4491
10    4482
0     4442
Name: count, dtype: int64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 30 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                50000 non-null  int64
 1   Age                               50000 non-null  int64
 2   Gender                            50000 non-null  object
 3   Marital_Status                    50000 non-null  object
 4   Job_Role                          50000 non-null  object
 5   Experience_Years                  50000 non-null  int64
 6   Monthly_Salary_INR                50000 non-null  float64
 7   Working_Hours_per_Week            50000 non-null  int64
 8   Commute_Time_Hours                50000 non-null  float64
 9   Remote_Work                       50000 non-null  bool
 10  Stress_Level                      50000 non-null  int64
 11  Health_Issues                     37459 non-null  object
 12  Company_Size                      50000 non-null  object
 13  Department                        50000 non-null  object
 14  Sleep_Hours                       50000 non-null  float64
 15  Physical_Activity_Hours_per_Week  50000 non-null  float64
 16  Mental_Health_Leave_Taken         50000 non-null  bool
 17  Manager_Support_Level             50000 non-null  int64
 18  Work_Pressure_Level               50000 non-null  int64
 19  Annual_Leaves_Taken               50000 non-null  int64
 20  Work_Life_Balance                 50000 non-null  int64
 21  Family_Support_Level              50000 non-null  int64
 22  Job_Satisfaction                  50000 non-null  int64
 23  Performance_Rating                50000 non-null  int64
 24  Team_Size                         50000 non-null  int64
 25  Training_Opportunities            50000 non-null  bool
 26  Gender_Bias_Experienced           50000 non-null  bool
 27  Discrimination_Experienced        50000 non-null  bool
 28  Burnout_Symptoms                  50000 non-null  object
 29  Location                          50000 non-null  object
dtypes: bool(5), float64(4), int64(13), object(8)
memory usage: 9.8+ MB

In [21]:
df.isnull().sum()

ID                                      0
Age                                     0
Gender                                  0
Marital_Status                          0
Job_Role                                0
Experience_Years                        0
Monthly_Salary_INR                      0
Working_Hours_per_Week                  0
Commute_Time_Hours                      0
Remote_Work                             0
Stress_Level                            0
Health_Issues                       12541
Company_Size                            0
Department                              0
Sleep_Hours                             0
Physical_Activity_Hours_per_Week        0
Mental_Health_Leave_Taken               0
Manager_Support_Level                   0
Work_Pressure_Level                     0
Annual_Leaves_Taken                     0
Work_Life_Balance                       0
Family_Support_Level                    0
Job_Satisfaction                        0
Performance_Rating                      0
Team_Size                               0
Training_Opportunities                  0
Gender_Bias_Experienced                 0
Discrimination_Experienced              0
Burnout_Symptoms                        0
Location                                0
dtype: int64

In [22]:
(12541/50000)*100

25.081999999999997

In [23]:
df['Health_Issues'].fillna(df['Health_Issues'].mode()[0],inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_24780\3653581166.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Health_Issues'].fillna(df['Health_Issues'].mode()[0],inplace=True)

In [24]:
df.duplicated().sum()

0

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 30 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                50000 non-null  int64
 1   Age                               50000 non-null  int64
 2   Gender                            50000 non-null  object
 3   Marital_Status                    50000 non-null  object
 4   Job_Role                          50000 non-null  object
 5   Experience_Years                  50000 non-null  int64
 6   Monthly_Salary_INR                50000 non-null  float64
 7   Working_Hours_per_Week            50000 non-null  int64
 8   Commute_Time_Hours                50000 non-null  float64
 9   Remote_Work                       50000 non-null  bool
 10  Stress_Level                      50000 non-null  int64
 11  Health_Issues                     50000 non-null  object
 12  Company_Size                      50000 non-null  object
 13  Department                        50000 non-null  object
 14  Sleep_Hours                       50000 non-null  float64
 15  Physical_Activity_Hours_per_Week  50000 non-null  float64
 16  Mental_Health_Leave_Taken         50000 non-null  bool
 17  Manager_Support_Level             50000 non-null  int64
 18  Work_Pressure_Level               50000 non-null  int64
 19  Annual_Leaves_Taken               50000 non-null  int64
 20  Work_Life_Balance                 50000 non-null  int64
 21  Family_Support_Level              50000 non-null  int64
 22  Job_Satisfaction                  50000 non-null  int64
 23  Performance_Rating                50000 non-null  int64
 24  Team_Size                         50000 non-null  int64
 25  Training_Opportunities            50000 non-null  bool
 26  Gender_Bias_Experienced           50000 non-null  bool
 27  Discrimination_Experienced        50000 non-null  bool
 28  Burnout_Symptoms                  50000 non-null  object
 29  Location                          50000 non-null  object
dtypes: bool(5), float64(4), int64(13), object(8)
memory usage: 9.8+ MB

In [26]:
df.describe()

,ID,Age,Experience_Years,Monthly_Salary_INR,Working_Hours_per_Week,Commute_Time_Hours,Stress_Level,Sleep_Hours,Physical_Activity_Hours_per_Week,Manager_Support_Level,Work_Pressure_Level,Annual_Leaves_Taken,Work_Life_Balance,Family_Support_Level,Job_Satisfaction,Performance_Rating,Team_Size
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.00000
mean,25000.500000,41.518600,20.071580,110129.926165,62.53824,1.500454,5.004680,6.498888,5.011624,5.004120,5.004420,14.992300,4.996920,4.993940,4.98412,5.006940,50.49730
std,14433.901067,13.833279,11.835681,52069.676542,16.16981,0.867738,3.154745,1.437200,2.885061,3.160314,3.159614,8.943398,3.165728,3.160674,3.16003,3.176535,28.89238
min,1.000000,18.000000,0.000000,20001.960000,35.00000,0.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.00000
25%,12500.750000,30.000000,10.000000,64875.487500,49.00000,0.740000,2.000000,5.300000,2.500000,2.000000,2.000000,7.000000,2.000000,2.000000,2.00000,2.000000,25.00000
50%,25000.500000,41.000000,20.000000,110168.205000,62.00000,1.500000,5.000000,6.500000,5.000000,5.000000,5.000000,15.000000,5.000000,5.000000,5.00000,5.000000,51.00000
75%,37500.250000,54.000000,30.000000,155322.665000,77.00000,2.250000,8.000000,7.700000,7.500000,8.000000,8.000000,23.000000,8.000000,8.000000,8.00000,8.000000,75.00000
max,50000.000000,65.000000,40.000000,199992.800000,90.00000,3.000000,10.000000,9.000000,10.000000,10.000000,10.000000,30.000000,10.000000,10.000000,10.00000,10.000000,100.00000

In [27]:
df.set_index('ID',inplace=True)

In [28]:
df.select_dtypes('object').count()

Gender              50000
Marital_Status      50000
Job_Role            50000
Health_Issues       50000
Company_Size        50000
Department          50000
Burnout_Symptoms    50000
Location            50000
dtype: int64

In [ ]:
num_col=df.select_dtypes('number')
for col in num_col:
    sns.histplot(df[col],kde=True)
    plt.title(f'Histplot of {col}')
    plt.show()

In [33]:
columns=df.select_dtypes('object')
for col in columns:
    print(df[col].value_counts())
    print()

Gender
Female        16769
Male          16718
Non-Binary    16513
Name: count, dtype: int64

Marital_Status
Single      12569
Divorced    12515
Married     12499
Widowed     12417
Name: count, dtype: int64

Job_Role
Manager      8465
Sales        8376
Developer    8368
Analyst      8335
HR           8274
Support      8182
Name: count, dtype: int64

Health_Issues
Mental      25075
Both        12518
Physical    12407
Name: count, dtype: int64

Company_Size
Small     16836
Medium    16678
Large     16486
Name: count, dtype: int64

Department
Sales        8446
Finance      8425
Admin        8350
IT           8288
Marketing    8253
HR           8238
Name: count, dtype: int64

Burnout_Symptoms
Occasional    16677
No            16662
Yes           16661
Name: count, dtype: int64

Location
Tier-2    12524
Tier-1    12521
Metro     12514
Tier-3    12441
Name: count, dtype: int64

In [36]:
df['Remote_Work'].value_counts()

Remote_Work
True     25234
False    24766
Name: count, dtype: int64

In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

#Define features and target
X = df.drop(columns=['Stress_Level'])  # Drop the target column from features
y = df['Stress_Level']  # Target variable

#training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Train Random Forest Classifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

#Get feature importances
feature_importances = rf_model.feature_importances_
feature_names = X.columns

importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': feature_importances})
importance_df = importance_df.sort_values(by='Importance', ascending=False)

#top 10 most important features
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=importance_df.head(10), palette='viridis')
plt.title('Top 10 Features Affecting Stress Levels')
plt.xlabel('Importance Score')
plt.ylabel('Feature')
plt.show()

#Display the top 10 important features
print("\nTop 10 important features based on Random Forest:")
print(importance_df.head(10))

ValueError: could not convert string to float: 'Female'